services:
    postgres:
        image: postgres:18-alpine
        container_name: destinify-database
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "127.0.0.1:${POSTGRES_PORT}:5432"
        volumes:
            - destinify_postgres_data:/var/lib/postgresql
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
            interval: 5s
            timeout: 5s
            start_period: 10s

volumes:
    destinify_postgres_data:
